version: '3'
services:
  senec2openwb:
    image: ludgerm/senec2openwb
    build: .
    depends_on:
      mosquitto:
        condition: service_started
    volumes:
      - ./bin/dat:/app/dat
      # - ./bin/res:/app/res
    networks:
      - mosquitto_net
    user: ludger:ludger
    environment:
      - PUID=1000
      - PGID=1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 20s
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mosquitto_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 20s

networks:
  mosquitto_net:
    name: mosquitto_net
    driver: bridge
